# Generated by Django 5.0.6 on 2025-08-15 02:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('type', models.TextField(choices=[('Учебно-методическая работа', 'Educ Method'), ('Подготовка к учебным занятиям', 'Preparing'), ('Учебно-исследовательская работа', 'Scientific Search'), ('Организационная работа', 'Organization'), ('Работа по воспитанию обучающихся', 'Upbringing'), ('Повышение квалификации', 'Qualification'), ('Работа с обучающимися и абитуриентами', 'Work With Students')])),
                ('hours_count', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='IndPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('user_confirmed', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_confirmed', to=settings.AUTH_USER_MODEL)),
                ('user_created', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_created', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PlanWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('type', models.TextField(choices=[('Учебно-методическая работа', 'Educ Method'), ('Подготовка к учебным занятиям', 'Preparing'), ('Учебно-исследовательская работа', 'Scientific Search'), ('Организационная работа', 'Organization'), ('Работа по воспитанию обучающихся', 'Upbringing'), ('Повышение квалификации', 'Qualification'), ('Работа с обучающимися и абитуриентами', 'Work With Students')])),
                ('hours_count', models.FloatField(blank=True, null=True)),
                ('max_hours_count', models.FloatField(blank=True, null=True)),
                ('is_new', models.BooleanField(blank=True, null=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan', to='ind_plan.indplan')),
            ],
        ),
    ]
