# Generated by Django 5.0.14 on 2025-09-02 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ind_plan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='indplan',
            name='status',
            field=models.IntegerField(choices=[(0, 'Создан'), (1, 'Утвержден'), (2, 'Требуются правки')], default=0),
        ),
        migrations.AlterField(
            model_name='planwork',
            name='type',
            field=models.TextField(choices=[('Учебно-методическая работа', 'educ_method'), ('Подготовка к учебным занятиям', 'preparing'), ('Учебно-исследовательская работа', 'scientific_research'), ('Организационная работа', 'organization'), ('Работа по воспитанию обучающихся', 'upbringing'), ('Повышение квалификации', 'qualification'), ('Работа с обучающимися и абитуриентами', 'work_with_students')]),
        ),
        migrations.AlterField(
            model_name='work',
            name='type',
            field=models.TextField(choices=[('Учебно-методическая работа', 'educ_method'), ('Подготовка к учебным занятиям', 'preparing'), ('Учебно-исследовательская работа', 'scientific_research'), ('Организационная работа', 'organization'), ('Работа по воспитанию обучающихся', 'upbringing'), ('Повышение квалификации', 'qualification'), ('Работа с обучающимися и абитуриентами', 'work_with_students')]),
        ),
    ]
