# Generated by Django 5.0.14 on 2025-09-12 06:38

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ind_plan', '0002_indplan_status_alter_planwork_type_alter_work_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='indplan',
            name='year',
        ),
        migrations.AddField(
            model_name='indplan',
            name='zav',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zav', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='indplan',
            name='created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True),
        ),
        migrations.AlterField(
            model_name='indplan',
            name='status',
            field=models.IntegerField(choices=[(0, 'Создан'), (1, 'Ожидает рассмотрения'), (2, 'Утвержден'), (3, 'Требуются правки')], default=0),
        ),
    ]
