# Generated by Django 5.0.14 on 2025-09-16 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ind_plan', '0003_remove_indplan_year_indplan_zav_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='indplan',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
