# Generated by Django 5.0.14 on 2025-09-19 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ind_plan', '0004_indplan_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planwork',
            name='type',
            field=models.TextField(choices=[('Учебно-методическая работа', 'educ_method'), ('Подготовка к учебным занятиям', 'preparing'), ('Научно-исследовательская работа', 'scientific_research'), ('Организационно-методическая работа', 'organization'), ('Работа по воспитанию обучающихся', 'upbringing'), ('Повышение квалификации', 'qualification'), ('Работа с обучающимися и абитуриентами', 'work_with_students')]),
        ),
        migrations.AlterField(
            model_name='work',
            name='type',
            field=models.TextField(choices=[('Учебно-методическая работа', 'educ_method'), ('Подготовка к учебным занятиям', 'preparing'), ('Научно-исследовательская работа', 'scientific_research'), ('Организационно-методическая работа', 'organization'), ('Работа по воспитанию обучающихся', 'upbringing'), ('Повышение квалификации', 'qualification'), ('Работа с обучающимися и абитуриентами', 'work_with_students')]),
        ),
    ]
