# Generated by Django 5.0.14 on 2025-09-26 03:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ind_plan', '0005_alter_planwork_type_alter_work_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='planwork',
            old_name='is_new',
            new_name='is_done',
        ),
        migrations.RemoveField(
            model_name='planwork',
            name='hours_count',
        ),
        migrations.RemoveField(
            model_name='planwork',
            name='max_hours_count',
        ),
        migrations.RemoveField(
            model_name='work',
            name='hours_count',
        ),
        migrations.AddField(
            model_name='planwork',
            name='count_done',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='planwork',
            name='count_required',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='planwork',
            name='work',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='work', to='ind_plan.work'),
        ),
        migrations.AddField(
            model_name='work',
            name='is_multiple',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='planwork',
            name='name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='planwork',
            name='type',
            field=models.TextField(blank=True, choices=[('Научно-исследовательская работа', 'scientific_research'), ('Организационно-методическая работа', 'organization'), ('Работа по воспитанию обучающихся', 'upbringing'), ('Повышение квалификации', 'qualification'), ('Работа с обучающимися и абитуриентами', 'work_with_students')], null=True),
        ),
        migrations.AlterField(
            model_name='work',
            name='type',
            field=models.TextField(choices=[('Научно-исследовательская работа', 'scientific_research'), ('Организационно-методическая работа', 'organization'), ('Работа по воспитанию обучающихся', 'upbringing'), ('Повышение квалификации', 'qualification'), ('Работа с обучающимися и абитуриентами', 'work_with_students')]),
        ),
    ]
