# Generated by Django 5.0.14 on 2025-09-30 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ind_plan', '0006_rename_is_new_planwork_is_done_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planwork',
            name='work',
        ),
        migrations.AddField(
            model_name='planwork',
            name='work_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
