# Generated by Django 5.0.14 on 2025-09-30 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ind_plan', '0007_remove_planwork_work_planwork_work_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planwork',
            name='type',
            field=models.TextField(blank=True, choices=[('Научно-исследовательская работа', 'scientific_research'), ('Организационно-методическая работа', 'organization'), ('Работа по воспитанию обучающихся', 'upbringing'), ('Повышение квалификации', 'qualification'), ('Работа с обучающимися и абитуриентами', 'work_with_students'), ('Учебно-методическая работа', 'educ_method')], null=True),
        ),
        migrations.AlterField(
            model_name='work',
            name='type',
            field=models.TextField(choices=[('Научно-исследовательская работа', 'scientific_research'), ('Организационно-методическая работа', 'organization'), ('Работа по воспитанию обучающихся', 'upbringing'), ('Повышение квалификации', 'qualification'), ('Работа с обучающимися и абитуриентами', 'work_with_students'), ('Учебно-методическая работа', 'educ_method')]),
        ),
    ]
