# Generated by Django 5.0.14 on 2025-10-06 01:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ind_plan', '0008_alter_planwork_type_alter_work_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planwork',
            name='work_id',
        ),
        migrations.AddField(
            model_name='planwork',
            name='work',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='work', to='ind_plan.indplan'),
        ),
    ]
