# Generated by Django 5.0.14 on 2025-10-06 02:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ind_plan', '0009_remove_planwork_work_id_planwork_work'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planwork',
            name='work',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='work', to='ind_plan.work'),
        ),
    ]
