# Generated by Django 5.0.14 on 2025-10-10 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ind_plan', '0010_alter_planwork_work'),
    ]

    operations = [
        migrations.AddField(
            model_name='indplan',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
