# Generated by Django 5.0.14 on 2025-10-10 08:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ind_plan', '0011_indplan_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='indplan',
            name='comment',
        ),
        migrations.CreateModel(
            name='PlanComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField()),
                ('comment', models.TextField()),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ind_plan', to='ind_plan.indplan')),
            ],
        ),
    ]
