# Generated by Django 5.0.14 on 2025-10-14 06:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ind_plan', '0012_remove_indplan_comment_plancomment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plancomment',
            name='status',
        ),
        migrations.AddField(
            model_name='plancomment',
            name='autor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='author', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='plancomment',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
