# Generated by Django 5.0.14 on 2025-10-14 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ind_plan', '0013_remove_plancomment_status_plancomment_autor_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plancomment',
            old_name='autor',
            new_name='author',
        ),
    ]
