# Generated by Django 5.0.14 on 2025-10-14 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ind_plan', '0014_rename_autor_plancomment_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='planwork',
            name='additional_info',
            field=models.TextField(blank=True, null=True),
        ),
    ]
