# Generated by Django 5.0.14 on 2025-10-15 04:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ind_plan', '0015_planwork_additional_info'),
    ]

    operations = [
        migrations.RenameField(
            model_name='indplan',
            old_name='confirmed_at',
            new_name='accepted_at',
        ),
        migrations.AlterField(
            model_name='plancomment',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True),
        ),
    ]
