# Generated by Django 5.0.14 on 2025-10-15 04:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ind_plan', '0016_rename_confirmed_at_indplan_accepted_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='indplan',
            name='user_confirmed',
        ),
        migrations.AddField(
            model_name='indplan',
            name='user_accepted',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_accepted', to=settings.AUTH_USER_MODEL),
        ),
    ]
