# Generated by Django 5.0.14 on 2025-10-31 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ind_plan', '0017_remove_indplan_user_confirmed_indplan_user_accepted'),
    ]

    operations = [
        migrations.RenameField(
            model_name='planwork',
            old_name='count_done',
            new_name='hours_count',
        ),
        migrations.RemoveField(
            model_name='planwork',
            name='count_required',
        ),
        migrations.RemoveField(
            model_name='work',
            name='is_multiple',
        ),
        migrations.AddField(
            model_name='work',
            name='hours_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
