# Generated by Django 5.0.14 on 2025-11-01 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ind_plan', '0019_indplantemplate_remove_indplan_accepted_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='indplantemplate',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
