# Generated by Django 5.0.14 on 2025-11-01 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ind_plan', '0020_indplantemplate_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indplan',
            name='is_deleted',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='indplantemplate',
            name='is_deleted',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='plancomment',
            name='is_deleted',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='planwork',
            name='is_deleted',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='work',
            name='is_deleted',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
