# Generated by Django 5.0.14 on 2025-11-01 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ind_plan', '0021_alter_indplan_is_deleted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='indplantemplate',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
