# Generated by Django 5.0.14 on 2025-11-01 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ind_plan', '0022_indplantemplate_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='indplan',
            name='accepted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
