# Generated by Django 5.0.14 on 2025-11-01 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ind_plan', '0023_indplan_accepted_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
