# Generated by Django 5.0.14 on 2025-11-01 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ind_plan', '0024_work_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='order',
            field=models.IntegerField(db_default=0, default=0),
        ),
    ]
