export enum Permissions {
  can_upload_plx_files = 'can_upload_plx_files',
  can_use_generator = 'can_use_generator',
}

export interface PlanLineItem {
  status: string,
  link_id: number,
  person: number,
  id: number,
  dis: string,
  plan__abbrprofile: string,
  plan__startyear: string,
  newdisid: string,
  caf: string,
}

export interface PlanFileData {
  id: number,
  user_id: number,
  title: string,
  file: string,
  status: number,
  status_verbose: string,
}

export interface PlanDocumentData {
  id: number,
  created_at: string,
  updated_at: string,
  is_deleted: boolean,
  plan_id: number,
  name: string,
  type: number,
  synchronize: boolean,
  manual: boolean,
}

export interface PlanLineData {
  id: number,
  created_at: string,
  updated_at: string,
  is_deleted: boolean,
  plan_id: number,
  disid_id: number,
  dis: string,
  newdisid: string,
  mustbesdudied: number,
  hoursinzet: number,
  caf: number,
  nocalccontrol: boolean,
  type: number,
  viewpract: number,
  viewobject: number,
  kompetences: string,
  synchronize: boolean,
}

export interface PlanSemestrData {
  id: number,
  created_at: string,
  updated_at: string,
  is_deleted: boolean,
  planlineid_id: number,
  num: number,
  lekc: number,
  lab: number,
  pr: number,
  srs: number,
  ekzhour: number,
  zet: number,
  ekz: boolean,
  zach: boolean,
  kp_hour: number,
  kp: boolean,
  kr_hour: number,
  kr: boolean,
  zacho: number,
  eios: number,
}

export interface PlanIndicatorData {
  id: number,
  created_at: string,
  updated_at: string,
  is_deleted: boolean,
  planlineid_id: number,
  competence_index: string,
  competence: string,
  indicator_index: string,
  indicator: string,
}

export interface PlanData {
  id: number,
  created_at: string,
  updated_at: string,
  is_deleted: boolean,
  file_id: number,
  subtype: string,
  shifr: string,
  abbrprofile: string,
  studyform: string,
  studylevel: string,
  studyprog: string,
  elementsinweek: number,
  species: string,
  usernum: number,
  whoratif: string,
  planname: string,
  kafcode: number,
  startyear: number,
  dviga: boolean,
  gviga: boolean,
  igazetweek: number,
  igahourzet: number,
  semesteroncource: number,
  gosdate: string,
  lastshifr: string,
  napr_e: string,
  napr_t: string,
  vuzname: string,
  head: string,
  faculty: string,
}

export interface GeneratorListData {
  discpl: string,
  id_discpl: number,
  planlin: number,
  abbr: string,
  yr: number,
  id_admission: number,
  mira_id: number,
  type: number,
  person: string,
  id: number,
  status: number,
  status_verbose: string,
  kafcode: number,
  discode: string,
}

export interface GeneratorPlanLineData {
  id: number,
  plan_id: number,
  disid_id: number,
  dis: string,
  newdisid: string,
  mustbesdudied: number,
  hoursinzet: number,
  caf: number,
  nocalccontrol: boolean,
  type: number,
  viewpract: number,
  viewobject: number,
  kompetences: string,
  synchronize: boolean,
  semester: GeneratorSemestersData[],
  indicators: GeneratorIndicatorsData[],
}

export interface GeneratorSemestersData {
  id: number,
  planlineid_id: number,
  num: number,
  lekc: number,
  lab: number,
  pr: number,
  srs: number,
  ekzhour: number,
  zet: number,
  ekz: number,
  zach: boolean,
  kp_hour: number,
  kp: boolean,
  kr_hour: number,
  kr: boolean,
  zacho: boolean,
  eios: number
}

export interface GeneratorIndicatorsData {
  id: number,
  planlineid_id: number,
  competence_index: string,
  competence: string,
  indicator_index: string,
  indicator: string,
}

export interface GeneratorData {
  planlines: GeneratorPlanLineData[],
  id: number,
  cadmission: number,
  mira_id: number,
  person: number,
  status: number,
  status_verbose: string,
}
