# Generated by Django 5.0.6 on 2024-08-22 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IrbisData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idd', models.IntegerField()),
                ('irbisid', models.CharField(blank=True, max_length=64, null=True)),
                ('bib_disc', models.CharField(blank=True, max_length=500, null=True)),
                ('rubrica', models.CharField(blank=True, max_length=128, null=True)),
                ('title', models.CharField(blank=True, max_length=250, null=True)),
                ('avtors', models.CharField(blank=True, max_length=200, null=True)),
                ('cnt', models.IntegerField(blank=True, null=True)),
                ('year_izd', models.IntegerField(blank=True, null=True)),
                ('http_link', models.CharField(blank=True, max_length=200, null=True)),
                ('izd_type', models.CharField(blank=True, max_length=16, null=True)),
                ('place', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'irbisdata',
                'managed': False,
            },
        ),
    ]
