# Generated by Django 5.0.6 on 2025-07-24 04:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Indicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('name', models.TextField(verbose_name='Название показателя')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RopMonitoring',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('name', models.TextField(verbose_name='Название мониторинга')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RopMonitoringScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('admission', models.IntegerField(verbose_name='Программа')),
                ('person', models.IntegerField(verbose_name='РОП')),
                ('score', models.FloatField(verbose_name='Кол-во баллов')),
                ('indicator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rop_monitoring.indicator', verbose_name='Индикатор')),
                ('rop_monitoring', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rop_monitoring.ropmonitoring', verbose_name='Мониторинг')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
