# Generated by Django 5.0.6 on 2025-07-24 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rop_monitoring', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ropmonitoringscore',
            name='rop_monitoring',
            field=models.IntegerField(default=0, verbose_name='Мониторинг'),
            preserve_default=False,
        ),
    ]
