# Generated by Django 5.0.6 on 2025-07-24 06:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rop_monitoring', '0002_ropmonitoringscore_rop_monitoring'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ropmonitoringscore',
            name='rop_monitoring',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rop_monitoring.ropmonitoring', verbose_name='Мониторинг'),
        ),
    ]
