# Generated by Django 5.0.6 on 2025-07-24 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rop_monitoring', '0003_alter_ropmonitoringscore_rop_monitoring'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ropmonitoringscore',
            name='score',
            field=models.FloatField(null=True, verbose_name='Кол-во баллов'),
        ),
    ]
