# Generated by Django 5.0.6 on 2025-07-28 02:25

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rop_monitoring', '0004_alter_ropmonitoringscore_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicator',
            name='types',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(choices=[(0, 'ООП бакалавриата, специалитета'), (1, 'ООП магистратуры'), (2, 'Новые ООП бакалавриата, специалитета'), (3, 'Новые ООП магистратуры')]), blank=True, default=list, size=None, verbose_name='Типы показателя'),
        ),
    ]
