# Generated by Django 5.0.6 on 2025-07-28 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rop_monitoring', '0006_alter_indicator_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicator',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание показателя'),
        ),
    ]
