# Generated by Django 5.0.6 on 2025-07-28 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rop_monitoring', '0007_indicator_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='ropmonitoringscore',
            name='value_boolean',
            field=models.BooleanField(null=True, verbose_name='Значение показателя (булевое)'),
        ),
        migrations.AddField(
            model_name='ropmonitoringscore',
            name='value_numeric',
            field=models.FloatField(null=True, verbose_name='Значение показателя (численное)'),
        ),
    ]
