# Generated by Django 5.0.6 on 2025-07-29 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rop_monitoring', '0008_ropmonitoringscore_value_boolean_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='indicator',
            old_name='types',
            new_name='admission_kinds',
        ),
        migrations.AddField(
            model_name='ropmonitoringscore',
            name='admission_name',
            field=models.TextField(blank=True, null=True, verbose_name='Название ООП'),
        ),
        migrations.AddField(
            model_name='ropmonitoringscore',
            name='person_name',
            field=models.TextField(blank=True, null=True, verbose_name='ФИО РОПа'),
        ),
        migrations.AlterField(
            model_name='ropmonitoringscore',
            name='admission',
            field=models.IntegerField(null=True, verbose_name='Программа'),
        ),
        migrations.AlterField(
            model_name='ropmonitoringscore',
            name='person',
            field=models.IntegerField(null=True, verbose_name='РОП'),
        ),
    ]
