# Generated by Django 5.0.6 on 2025-08-12 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rop_monitoring', '0009_rename_types_indicator_admission_kinds_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ropmonitoring',
            name='year',
            field=models.IntegerField(default=2025, verbose_name='Год'),
            preserve_default=False,
        ),
    ]
