# Generated by Django 5.0.14 on 2025-08-25 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rop_monitoring', '0010_ropmonitoring_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ropmonitoring',
            name='year',
            field=models.IntegerField(blank=True, null=True, verbose_name='Год'),
        ),
    ]
