# Generated by Django 5.0.14 on 2025-09-02 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rop_monitoring', '0011_alter_ropmonitoring_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='ropmonitoringscore',
            name='admission_kind',
            field=models.IntegerField(blank=True, null=True, verbose_name='Уровень ООП'),
        ),
    ]
