# Generated by Django 5.0.14 on 2025-09-03 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rop_monitoring', '0012_ropmonitoringscore_admission_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='ropmonitoringscore',
            name='admission_cdirection',
            field=models.IntegerField(blank=True, null=True, verbose_name='Направление'),
        ),
        migrations.AddField(
            model_name='ropmonitoringscore',
            name='admission_cprofili',
            field=models.IntegerField(blank=True, null=True, verbose_name='Профиль'),
        ),
        migrations.AddField(
            model_name='ropmonitoringscore',
            name='admission_cspec',
            field=models.IntegerField(blank=True, null=True, verbose_name='Специальность'),
        ),
    ]
