# Generated by Django 5.0.14 on 2025-09-04 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rop_monitoring', '0013_ropmonitoringscore_admission_cdirection_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ropmonitoringscore',
            name='count',
            field=models.IntegerField(null=True, verbose_name='Кол-во студентов/сотрудников'),
        ),
        migrations.AddField(
            model_name='ropmonitoringscore',
            name='res',
            field=models.IntegerField(null=True, verbose_name='Числитель(кол-во прошедших опрос)'),
        ),
    ]
