# Generated by Django 5.0.14 on 2025-09-04 03:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rop_monitoring', '0014_ropmonitoringscore_count_ropmonitoringscore_res'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ropmonitoringscore',
            old_name='count',
            new_name='count_sop',
        ),
        migrations.RenameField(
            model_name='ropmonitoringscore',
            old_name='res',
            new_name='res_sop',
        ),
    ]
