# Generated by Django 5.0.14 on 2025-09-04 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rop_monitoring', '0015_rename_count_ropmonitoringscore_count_sop_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ropmonitoringscore',
            old_name='count_sop',
            new_name='count',
        ),
        migrations.RenameField(
            model_name='ropmonitoringscore',
            old_name='res_sop',
            new_name='res',
        ),
    ]
