# Generated by Django 5.0.14 on 2025-09-10 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rop_monitoring', '0016_rename_count_sop_ropmonitoringscore_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ropmonitoringscore',
            name='responded',
            field=models.IntegerField(null=True, verbose_name='Кол-во сотрудников'),
        ),
        migrations.AddField(
            model_name='ropmonitoringscore',
            name='total',
            field=models.IntegerField(null=True, verbose_name='Числитель(кол-во прошедших опрос)'),
        ),
    ]
