# Generated by Django 5.0.14 on 2025-11-01 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rop_monitoring', '0017_ropmonitoringscore_responded_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicator',
            name='is_deleted',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='ropmonitoring',
            name='is_deleted',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='ropmonitoringscore',
            name='is_deleted',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
