# Generated by Django 5.0.6 on 2024-10-30 05:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('generator', '0027_alter_formcontrol_type_alter_independenttypes_type'),
        ('rpd', '0034_documentstypes_basedocuments_new_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('title', models.TextField()),
                ('file', models.FileField(upload_to='uploads/files/%Y-%m-%d/')),
                ('line', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='generator.planlineslink')),
                ('rpd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rpd.plandata')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rpd.documentstypes')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
