# Generated by Django 5.0.6 on 2024-11-21 02:31

import django.db.models.deletion
import uplfile.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rpd', '0036_alter_rpdfile_file'),
        ('uplfile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadfiles',
            name='file',
            field=models.FileField(upload_to=uplfile.models.get_upload_dir),
        ),
        migrations.AlterField(
            model_name='uploadfiles',
            name='rpd',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uplfile', to='rpd.plandata'),
        ),
    ]
