# Generated by Django 5.0.14 on 2025-11-01 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uplfile', '0002_alter_uploadfiles_file_alter_uploadfiles_rpd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadfiles',
            name='is_deleted',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
