# Generated by Django 5.0.6 on 2024-07-30 02:16
from django.contrib.postgres.fields import ArrayField

import app.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='permissions',
            field=ArrayField(base_field=models.TextField(choices=[('can_upload_plx_files', 'Может загружать plx файлы')]), blank=True, default=list, size=None),
        ),
    ]
