# Generated by Django 5.0.6 on 2024-08-07 08:46

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0002_userprofile_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='permissions',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(choices=[('can_upload_plx_files', 'Может загружать plx файлы'), ('can_edit_rpd', 'Может редактировать РПД')]), blank=True, default=list, size=None),
        ),
    ]
