# Generated by Django 5.0.6 on 2025-03-20 05:35

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0006_userprofile_middle_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='permissions',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(choices=[('can_upload_plx_files', 'Может загружать plx файлы'), ('can_edit_rpd', 'Может редактировать РПД'), ('can_use_generator', 'Может использовать генератор'), ('can_upload_files', 'Может загружать файлы Программы'), ('scientific_admin', 'Просмотр всех ПНД по программе аспирантуры')]), blank=True, default=list, size=None),
        ),
    ]
