# Generated by Django 5.0.14 on 2025-08-21 03:46

from django.db import migrations


def my_function(apps, schema_editor):
    UserProfile = apps.get_model("auths", "UserProfile")
    ESIAUser = apps.get_model("esia_login", "ESIAUser")

    user_data = UserProfile.objects.all()

    for user in user_data:
        ESIAUser.objects.get_or_create(user=user.user, mira_id=user.mira_id)

class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0008_alter_userprofile_permissions'),
    ]

    operations = [
        migrations.RunPython(my_function, migrations.RunPython.noop),
    ]
