# Generated by Django 5.0.14 on 2026-02-25 04:13

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0010_alter_userprofile_is_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='permissions',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(choices=[('can_upload_plx_files', 'Может загружать plx файлы'), ('can_edit_rpd', 'Может редактировать РПД'), ('can_use_generator', 'Может использовать генератор'), ('can_upload_files', 'Может загружать файлы Программы'), ('scientific_admin', 'Просмотр всех ПНД по программе аспирантуры'), ('can_monitor_rops', 'Может мониторить РОПов'), ('can_use_competence_passport_generator', 'Может использовать генратор паспорта компетенций'), ('can_edit_competence_passport', 'Может редактировать паспорт компетенций')]), blank=True, default=list, size=None),
        ),
    ]
