# Generated by Django 5.0.6 on 2024-08-09 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UchPlanPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('species', models.CharField(blank=True, max_length=4096, null=True)),
                ('studyprog', models.CharField(blank=True, max_length=64, null=True)),
                ('studyform', models.CharField(blank=True, max_length=16, null=True)),
                ('fullplanname', models.CharField(blank=True, max_length=256, null=True)),
                ('name', models.CharField(blank=True, max_length=256, null=True)),
                ('kafcode', models.CharField(blank=True, max_length=256, null=True)),
                ('ckaf', models.IntegerField(blank=True, null=True)),
                ('lastshifr', models.CharField(blank=True, max_length=64, null=True)),
                ('abbrprofile', models.CharField(blank=True, max_length=16, null=True)),
                ('startyear', models.IntegerField(blank=True, null=True)),
                ('gosdate', models.CharField(blank=True, max_length=16, null=True)),
                ('gosdocument', models.IntegerField(blank=True, null=True)),
                ('gostype', models.FloatField(blank=True, null=True)),
                ('additiondate', models.CharField(blank=True, max_length=16, null=True)),
                ('cadmission', models.IntegerField(blank=True, null=True)),
                ('fordel', models.CharField(choices=[('t', 'True'), ('f', 'False')], default='f', max_length=1)),
                ('cperson', models.IntegerField(blank=True, null=True)),
                ('cobrazstandart', models.IntegerField(blank=True, null=True)),
                ('moved', models.CharField(choices=[('t', 'True'), ('f', 'False')], max_length=1)),
                ('guid', models.CharField(blank=True, max_length=64, null=True)),
            ],
            options={
                'db_table': 'uchplan_plan',
                'managed': False,
            },
        ),
    ]
