# Generated by Django 5.0.6 on 2024-08-13 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arim', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Catadmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yr', models.IntegerField()),
                ('abbr', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'catadmission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UchPlanDiscpl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
            ],
            options={
                'db_table': 'uchplan_discpl',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UchPlanKaf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ckaf2istu', models.IntegerField()),
                ('ckaf2rpgen', models.IntegerField()),
                ('name2rpgen', models.CharField(max_length=250)),
                ('ckaf2asp', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'uchplan_kaf',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UchPlanLines',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cperson', models.IntegerField(blank=True, null=True)),
                ('newdisid', models.CharField(blank=True, max_length=32, null=True)),
                ('iddis', models.CharField(blank=True, max_length=32, null=True)),
                ('kompetences', models.CharField(blank=True, max_length=2048, null=True)),
                ('mustbesdudied', models.IntegerField(blank=True, null=True)),
                ('hoursinzet', models.IntegerField(blank=True, null=True)),
                ('ckaf', models.IntegerField(blank=True, null=True)),
                ('nocalccontrol', models.IntegerField(blank=True, null=True)),
                ('fordel', models.CharField(choices=[('t', 'True'), ('f', 'False')], default='f', max_length=1)),
                ('type', models.IntegerField(blank=True, null=True)),
                ('viewobject', models.IntegerField(blank=True, null=True)),
                ('viewpract', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'uchplan_lines',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UchPlanSemestr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField()),
                ('lekc', models.IntegerField(blank=True, null=True)),
                ('lab', models.IntegerField(blank=True, null=True)),
                ('pr', models.IntegerField(blank=True, null=True)),
                ('srs', models.IntegerField(blank=True, null=True)),
                ('ekzhour', models.IntegerField(blank=True, null=True)),
                ('zet', models.IntegerField(blank=True, null=True)),
                ('ekz', models.CharField(blank=True, choices=[('t', 'True'), ('f', 'False')], max_length=1, null=True)),
                ('zach', models.CharField(blank=True, choices=[('t', 'True'), ('f', 'False')], max_length=1, null=True)),
                ('kp', models.CharField(blank=True, choices=[('t', 'True'), ('f', 'False')], max_length=1, null=True)),
                ('kp_hour', models.IntegerField()),
                ('kr', models.CharField(blank=True, choices=[('t', 'True'), ('f', 'False')], max_length=1, null=True)),
                ('kr_hour', models.IntegerField()),
                ('zacho', models.IntegerField()),
                ('eios', models.IntegerField()),
            ],
            options={
                'db_table': 'uchplan_semestr',
                'managed': False,
            },
        ),
    ]
