# Generated by Django 5.0.6 on 2024-08-22 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arim', '0002_catadmission_uchplandiscpl_uchplankaf_uchplanlines_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatAud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=16, null=True)),
                ('ckaf', models.IntegerField(null=True)),
                ('cnazn', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'cataud',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ClLicense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
            options={
                'db_table': 'cl$license',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OborudData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('inv', models.CharField(blank=True, max_length=12, null=True)),
                ('ismobile', models.CharField(choices=[('t', 'True'), ('f', 'False')], max_length=1)),
            ],
            options={
                'db_table': 'oborud_data',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UistLicense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnt', models.IntegerField()),
            ],
            options={
                'db_table': 'uistlicense',
                'managed': False,
            },
        ),
    ]
