# Generated by Django 5.0.6 on 2024-08-29 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arim', '0003_cataud_cllicense_oboruddata_uistlicense'),
    ]

    operations = [
        migrations.CreateModel(
            name='UchPlanFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('ctype', models.IntegerField()),
                ('fordel', models.CharField(choices=[('t', 'True'), ('f', 'False')], default='f', max_length=1)),
            ],
            options={
                'db_table': 'uchplan_files',
                'managed': False,
            },
        ),
    ]
