# Generated by Django 5.0.6 on 2024-10-11 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arim', '0004_uchplanfiles'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatFaculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('dean', models.CharField(max_length=128)),
                ('cdean', models.IntegerField()),
            ],
            options={
                'db_table': 'catfaculty',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CatKaf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('zav', models.CharField(max_length=50)),
                ('czav', models.IntegerField()),
            ],
            options={
                'db_table': 'catkaf',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CatPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('prepod', models.CharField(choices=[('t', 'True'), ('f', 'False')], default='f', max_length=1)),
            ],
            options={
                'db_table': 'catperson',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CLAdmKind',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('name_prof', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'cl$admkind',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CLDirection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('cod', models.CharField(max_length=8)),
            ],
            options={
                'db_table': 'cl$direction',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CLFob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
            options={
                'db_table': 'cl$fob',
                'managed': False,
            },
        ),
    ]
