# Generated by Django 5.0.6 on 2024-10-29 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arim', '0005_catfaculty_catkaf_catperson_cladmkind_cldirection_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RpdUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('isadmin', models.CharField(choices=[('t', 'True'), ('f', 'False')], max_length=1)),
                ('isspo', models.CharField(choices=[('t', 'True'), ('f', 'False')], max_length=1)),
                ('isspoadm', models.CharField(choices=[('t', 'True'), ('f', 'False')], max_length=1)),
            ],
            options={
                'db_table': 'rpdusers',
                'managed': False,
            },
        ),
    ]
