# Generated by Django 5.0.6 on 2025-03-31 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arim', '0006_rpdusers'),
    ]

    operations = [
        migrations.CreateModel(
            name='CLSpec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('code', models.CharField(max_length=8)),
                ('cprepod', models.IntegerField()),
            ],
            options={
                'db_table': 'cl$spec',
                'managed': False,
            },
        ),
    ]
