# Generated by Django 5.0.6 on 2025-05-13 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arim', '0007_clspec'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatDepartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameshort', models.CharField(max_length=512)),
                ('name', models.CharField(max_length=512)),
            ],
            options={
                'db_table': 'catdep',
                'managed': False,
            },
        ),
    ]
