# Generated by Django 5.0.6 on 2025-08-14 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arim', '0008_catdepartment'),
    ]

    operations = [
        migrations.CreateModel(
            name='UchNagr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('discpl', models.CharField(max_length=1000)),
                ('grup', models.CharField(max_length=10)),
                ('hour', models.IntegerField()),
                ('sem', models.IntegerField()),
                ('metka', models.CharField(max_length=10)),
                ('direction', models.CharField(max_length=50)),
                ('realhour', models.FloatField()),
                ('doljnost', models.CharField(max_length=50)),
                ('done', models.BooleanField()),
                ('ddat', models.DateTimeField()),
            ],
            options={
                'db_table': 'person2uchnagr',
                'managed': False,
            },
        ),
    ]
