# Generated by Django 5.0.14 on 2025-08-25 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arim', '0008_catdepartment'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatStud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
            options={
                'db_table': 'catstud',
                'managed': False,
            },
        ),
    ]
