# Generated by Django 5.0.14 on 2025-11-01 12:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arim', '0009_catstud'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person2Uchnagr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c1pers', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('discpl', models.TextField()),
                ('grup', models.CharField(max_length=50)),
                ('hour', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('formcontr', models.CharField(max_length=50)),
                ('sem', models.IntegerField()),
                ('metka', models.CharField(max_length=50)),
                ('kurs', models.IntegerField()),
                ('direction', models.CharField(max_length=255)),
                ('realhour', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('doljnost', models.CharField(max_length=255)),
                ('studcount', models.IntegerField()),
                ('ddat', models.DateTimeField(blank=True, null=True)),
                ('snapshot_time', models.DateTimeField(blank=True, null=True)),
                ('year', models.IntegerField()),
                ('cadmission', models.ForeignKey(db_column='cadmission', on_delete=django.db.models.deletion.CASCADE, to='arim.catadmission')),
                ('cperson', models.ForeignKey(db_column='cperson', on_delete=django.db.models.deletion.CASCADE, to='arim.catperson')),
            ],
            options={
                'verbose_name': 'Академическая нагрузка',
                'verbose_name_plural': 'Академические нагрузки',
                'db_table': 'person2uchnagr',
            },
        ),
    ]
