# Generated by Django 5.0.6 on 2025-06-04 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prof_activity', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='areas2planprofactivity',
            name='user',
        ),
        migrations.RemoveField(
            model_name='type2planprofactivity',
            name='user',
        ),
        migrations.AddField(
            model_name='areas2planprofactivity',
            name='user_mira_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='type2planprofactivity',
            name='user_mira_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
