# Generated by Django 5.0.14 on 2025-11-01 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prof_activity', '0003_auto_20250610_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='areas2planprofactivity',
            name='is_deleted',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='areasprofactivity',
            name='is_deleted',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='type2planprofactivity',
            name='is_deleted',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='typeprofactivity',
            name='is_deleted',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
