# Generated by Django 5.0.6 on 2024-08-13 06:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rpd', '0028_plandata_mira_id_plandocuments_mira_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanLinesLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('cadmission', models.IntegerField(verbose_name='')),
                ('mira_id', models.IntegerField(verbose_name='')),
                ('person', models.IntegerField(verbose_name='')),
                ('status', models.IntegerField(choices=[(1, 'Назначен'), (2, 'Заполняется'), (3, 'Отправлен на проверку'), (4, 'Подтвержден'), (5, 'Требуются правки')], default=1)),
                ('planlines', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rpd.linesdata', verbose_name='')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
