# Generated by Django 5.0.6 on 2024-08-16 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planlineslink',
            name='status',
            field=models.IntegerField(choices=[(0, 'Назначен'), (1, 'Заполняется'), (2, 'Отправлен на проверку'), (3, 'Подтвержден'), (4, 'Требуются правки')], default=0),
        ),
    ]
