# Generated by Django 5.0.6 on 2024-08-22 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0003_currentcontrol'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CurrentControl',
            new_name='FormControl',
        ),
    ]
