# Generated by Django 5.0.6 on 2024-08-23 05:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0005_independenttypes'),
        ('rpd', '0030_alter_linesdata_plan'),
    ]

    operations = [
        migrations.CreateModel(
            name='DisciplineIndicators',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('know', models.TextField(blank=True, null=True)),
                ('able', models.TextField(blank=True, null=True)),
                ('own', models.TextField(blank=True, null=True)),
                ('criteria', models.TextField(blank=True, null=True)),
                ('methods', models.TextField(blank=True, null=True)),
                ('indicator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discipline_indicator', to='rpd.linesindicators')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
