# Generated by Django 5.0.6 on 2024-08-23 05:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0006_disciplineindicators'),
        ('rpd', '0030_alter_linesdata_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='disciplineindicators',
            name='planlineid',
            field=models.ForeignKey(default=773, on_delete=django.db.models.deletion.CASCADE, to='rpd.linesdata'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='disciplineindicators',
            name='indicator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rpd.linesindicators'),
        ),
    ]
