# Generated by Django 5.0.6 on 2024-08-25 15:39

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0007_disciplineindicators_planlineid_and_more'),
        ('rpd', '0030_alter_linesdata_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='planlineslink',
            name='precedence_discipline',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(verbose_name=''), blank=True, default=[], null=True, size=None),
        ),
        migrations.AddField(
            model_name='planlineslink',
            name='subsequent_discipline',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(verbose_name=''), blank=True, default=[], null=True, size=None),
        ),
        migrations.AlterField(
            model_name='disciplineindicators',
            name='indicator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discipline_indicator', to='rpd.linesindicators'),
        ),
    ]
