# Generated by Django 5.0.6 on 2024-08-26 06:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0008_planlineslink_precedence_discipline_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DisciplineThemes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('name', models.TextField()),
                ('hours', models.FloatField()),
                ('semester', models.IntegerField()),
                ('comment', models.TextField()),
                ('formcontrol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='generator.formcontrol')),
                ('planlineslink', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='generator.planlineslink')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
