# Generated by Django 5.0.6 on 2024-08-27 05:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0009_disciplinethemes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disciplinethemes',
            name='hours',
        ),
        migrations.AlterField(
            model_name='disciplinethemes',
            name='planlineslink',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discipline_themes', to='generator.planlineslink'),
        ),
    ]
