# Generated by Django 5.0.6 on 2024-08-28 03:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0010_remove_disciplinethemes_hours_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DisciplineWorkHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('type', models.IntegerField(choices=[(0, 'Лекции'), (1, 'Практики'), (2, 'Самостоятельные'), (3, 'Лабораторные')])),
                ('name', models.TextField()),
                ('hours', models.IntegerField()),
                ('planlineslink', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='generator.planlineslink')),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='generator.disciplinethemes')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
