# Generated by Django 5.0.6 on 2024-08-28 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0011_disciplineworkhours'),
    ]

    operations = [
        migrations.AddField(
            model_name='disciplineworkhours',
            name='semester',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
