# Generated by Django 5.0.6 on 2024-08-28 07:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0012_disciplineworkhours_semester'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disciplineworkhours',
            name='hours',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='disciplineworkhours',
            name='planlineslink',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discipline_work_hour', to='generator.planlineslink'),
        ),
    ]
