# Generated by Django 5.0.6 on 2024-08-30 07:49

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0013_alter_disciplineworkhours_hours_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='planlineslink',
            name='library',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='planlineslink',
            name='logistics',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='planlineslink',
            name='software',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='planlineslink',
            name='precedence_discipline',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(verbose_name=''), blank=True, default=list, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='planlineslink',
            name='subsequent_discipline',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(verbose_name=''), blank=True, default=list, null=True, size=None),
        ),
    ]
