# Generated by Django 5.0.6 on 2024-09-30 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0014_planlineslink_library_planlineslink_logistics_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='planlineslink',
            name='interactive_methods',
            field=models.TextField(blank=True, null=True),
        ),
    ]
