# Generated by Django 5.0.6 on 2024-10-01 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0015_planlineslink_interactive_methods'),
    ]

    operations = [
        migrations.CreateModel(
            name='DefaultsResources',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('name', models.TextField(verbose_name='Наименование ресурса')),
                ('url', models.TextField(blank=True, null=True, verbose_name='Ссылка на ресурс')),
                ('type', models.IntegerField(choices=[(0, 'Интернет'), (1, 'База данных')])),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
