# Generated by Django 5.0.6 on 2024-10-03 01:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0016_defaultsresources'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('type', models.TextField()),
                ('value', models.JSONField()),
                ('planlineslink', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_info', to='generator.planlineslink')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
