# Generated by Django 5.0.6 on 2024-10-02 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0017_additionalinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionalinfo',
            name='value',
            field=models.JSONField(),
        ),
    ]
