# Generated by Django 5.0.6 on 2024-10-03 02:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0018_alter_additionalinfo_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planlineslink',
            name='library',
        ),
    ]
