# Generated by Django 5.0.6 on 2024-10-03 02:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0019_remove_planlineslink_library'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planlineslink',
            name='software',
        ),
    ]
