# Generated by Django 5.0.6 on 2024-10-03 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0020_remove_planlineslink_software'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planlineslink',
            name='logistics',
        ),
    ]
