# Generated by Django 5.0.6 on 2024-10-03 03:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0021_remove_planlineslink_logistics'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planlineslink',
            name='precedence_discipline',
        ),
        migrations.RemoveField(
            model_name='planlineslink',
            name='subsequent_discipline',
        ),
    ]
