# Generated by Django 5.0.6 on 2024-10-03 03:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0022_remove_planlineslink_precedence_discipline_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planlineslink',
            name='interactive_methods',
        ),
    ]
