# Generated by Django 5.0.6 on 2024-10-11 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0023_remove_planlineslink_interactive_methods'),
    ]

    operations = [
        migrations.AddField(
            model_name='disciplineworkhours',
            name='num',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
