# Generated by Django 5.0.6 on 2024-10-11 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0024_disciplineworkhours_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='disciplinethemes',
            name='num',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
