# Generated by Django 5.0.6 on 2024-10-21 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0025_disciplinethemes_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='formcontrol',
            name='type',
            field=models.CharField(default=0, max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='independenttypes',
            name='type',
            field=models.CharField(default=0, max_length=64),
            preserve_default=False,
        ),
    ]
