# Generated by Django 5.0.6 on 2024-10-22 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0026_formcontrol_type_independenttypes_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formcontrol',
            name='type',
            field=models.CharField(max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='independenttypes',
            name='type',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
