# Generated by Django 5.0.6 on 2024-11-21 02:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0027_alter_formcontrol_type_alter_independenttypes_type'),
        ('rpd', '0036_alter_rpdfile_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='planlineslink',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='planlineslink',
            name='protocol_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='planlineslink',
            name='protocol_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='planlineslink',
            name='cadmission',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='planlineslink',
            name='mira_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='planlineslink',
            name='person',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='planlineslink',
            name='planlines',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rpd.linesdata'),
        ),
    ]
