# Generated by Django 5.0.6 on 2024-11-26 04:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0028_planlineslink_comment_planlineslink_protocol_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planlineslink',
            name='comment',
        ),
        migrations.CreateModel(
            name='PPlanLinesLinkComments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('comment', models.TextField()),
                ('planlineslink', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='generator.planlineslink')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
