# Generated by Django 5.0.6 on 2024-11-26 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0029_remove_planlineslink_comment_pplanlineslinkcomments'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PPlanLinesLinkComments',
            new_name='PlanLinesLinkComments',
        ),
    ]
