# Generated by Django 5.0.6 on 2024-11-27 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0030_rename_pplanlineslinkcomments_planlineslinkcomments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planlineslink',
            name='protocol_number',
            field=models.TextField(blank=True, null=True),
        ),
    ]
