# Generated by Django 5.0.6 on 2024-11-27 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0031_alter_planlineslink_protocol_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planlineslink',
            name='status',
            field=models.IntegerField(choices=[(0, 'Назначен'), (1, 'Заполняется'), (2, 'Отправлен на проверку'), (3, 'Утвержден'), (4, 'Требуются правки')], default=0),
        ),
    ]
