# Generated by Django 5.0.6 on 2024-12-04 05:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0032_alter_planlineslink_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='planlineslink',
            name='user_accepted',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='planlineslinkcomments',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
