# Generated by Django 5.0.6 on 2025-02-24 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0034_alter_planlineslink_user_accepted'),
    ]

    operations = [
        migrations.AddField(
            model_name='planlineslink',
            name='user_type',
            field=models.IntegerField(blank=True, choices=[(0, 'Руководитель программы'), (1, 'Заведующий кафедрой'), (2, 'Директор института')], default=None, null=True),
        ),
    ]
