# Generated by Django 5.0.6 on 2025-02-24 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0035_planlineslink_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='planlineslink',
            name='meeting',
            field=models.TextField(blank=True, null=True),
        ),
    ]
