# Generated by Django 5.0.6 on 2025-02-24 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0036_planlineslink_meeting'),
    ]

    operations = [
        migrations.AddField(
            model_name='planlineslink',
            name='accept_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='planlineslink',
            name='review_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
