# Generated by Django 5.0.6 on 2025-03-04 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0037_planlineslink_accept_date_planlineslink_review_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScientificPlanData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('cfac', models.TextField(blank=True, null=True)),
                ('cfob', models.TextField(blank=True, null=True)),
                ('ckaf', models.TextField(blank=True, null=True)),
                ('director', models.TextField(blank=True, null=True)),
                ('fgt', models.TextField(blank=True, null=True)),
                ('name', models.TextField(blank=True, null=True)),
                ('rng', models.CharField(blank=True, null=True)),
                ('rop', models.TextField(blank=True, null=True)),
                ('startyear', models.CharField(blank=True, null=True)),
                ('viceRector', models.TextField(blank=True, null=True)),
                ('year', models.CharField(blank=True, null=True)),
                ('zavkaf', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
