# Generated by Django 5.0.6 on 2025-03-04 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0038_scientificplandata'),
    ]

    operations = [
        migrations.AddField(
            model_name='scientificplandata',
            name='mira_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
