# Generated by Django 5.0.6 on 2025-03-05 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0039_scientificplandata_mira_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScientificWorkType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('name', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
