# Generated by Django 5.0.6 on 2025-03-05 08:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0040_scientificworktype'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScientificData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('text', models.TextField()),
                ('parameters', models.JSONField()),
                ('plan_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='generator.scientificplandata')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
