# Generated by Django 5.0.6 on 2025-03-05 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0041_scientificdata'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scientificdata',
            old_name='plan_id',
            new_name='plan',
        ),
    ]
