# Generated by Django 5.0.6 on 2025-03-10 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0042_rename_plan_id_scientificdata_plan'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScientificDataDefault',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('text', models.TextField(verbose_name='Текст')),
                ('semester', models.IntegerField(verbose_name='Семестр')),
                ('order', models.IntegerField(verbose_name='Порядок')),
                ('kurs', models.IntegerField(verbose_name='Сколько курсов идет программа (3 или 4)')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
