# Generated by Django 5.0.6 on 2025-03-10 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0043_scientificdatadefault'),
    ]

    operations = [
        migrations.AddField(
            model_name='scientificdatadefault',
            name='part',
            field=models.IntegerField(choices=[(0, 'Примерный план выполнения научного исследования'), (1, 'Примерный план подготовки диссертации'), (2, 'Примерный план подготовки публикаций')], default=0),
            preserve_default=False,
        ),
    ]
