# Generated by Django 5.0.6 on 2025-05-13 05:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0044_scientificdatadefault_part'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='planlineslink',
            name='confirm_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='planlineslink',
            name='user_confirmed',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_plans', to=settings.AUTH_USER_MODEL, verbose_name='Кто согласовал, должен РОП'),
        ),
        migrations.AlterField(
            model_name='planlineslink',
            name='user_accepted',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accepted_plans', to=settings.AUTH_USER_MODEL, verbose_name='Кто утвердил, должен зав.каф'),
        ),
    ]
