# Generated by Django 5.0.6 on 2025-05-14 03:22

from django.db import migrations
from django.db.models import F


def update_user_confirmed(apps, schema_editor):
    PlanLinesLinkOld = apps.get_model("generator", "PlanLinesLink")
    PlanLinesLinkOld.objects.filter(status=3).update(
        user_confirmed=F('user_accepted')
    )

class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0045_planlineslink_confirm_date_and_more'),
    ]

    operations = [
        migrations.RunPython(update_user_confirmed)
    ]
