# Generated by Django 5.0.6 on 2025-05-16 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0046_auto_20250514_1122'),
    ]

    operations = [
        migrations.RunSQL("""
UPDATE generator_planlineslink
SET status = 3
WHERE id in (SELECT pl.id
             from generator_planlineslink pl
                      LEFT JOIN rpd_linesdata rl on pl.planlines_id = rl.id
             WHERE pl.status != 3
               and rl.dis in (
                              'Безопасность жизнедеятельности',
                              'Инженерная и компьютерная графика',
                              'Иностранный язык',
                              'Информационные технологии',
                              'История России',
                              'Критическое и системное мышление',
                              'Математика',
                              'Метрология, стандартизация, сертификация',
                              'Основы деловой коммуникации',
                              'Основы инклюзивного взаимодействия',
                              'Основы проектной деятельности',
                              'Основы российской государственности',
                              'Правоведение',
                              'Сопротивление материалов',
                              'Теоретическая механика',
                              'Физика',
                              'Физическая культура и спорт',
                              'Философия',
                              'Химия',
                              'Экономика',
                              'Элективные курсы по физической культуре',
                              'Электротехника и электроник',
                              'Академическое письмо',
                              'Иностранный язык для магистрантов',
                              'Философия наук'
                 )
               and user_accepted_id is not null)        
        """)
    ]
