# Generated by Django 5.0.6 on 2025-05-26 03:51

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0047_auto_20250516_2028'),
    ]

    operations = [
        migrations.AddField(
            model_name='disciplinethemes',
            name='formcontrol_list',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=list, null=True, size=None),
       ),
        migrations.RunSQL(f"""
            UPDATE generator_disciplinethemes SET formcontrol_list = ARRAY[formcontrol_id]
        """)
    ]
