# Generated by Django 5.0.6 on 2025-05-30 17:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0048_disciplinethemes_formcontrol_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disciplinethemes',
            name='formcontrol',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='generator.formcontrol'),
        ),
    ]
