# Generated by Django 5.0.6 on 2025-06-03 06:21
from django.core.management import call_command
from django.db import migrations


def func(*args, **kwargs):
    call_command("add_default_num_in_tat")

class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0049_alter_disciplinethemes_formcontrol'),
    ]

    operations = [
        migrations.RunPython(func)
    ]
