# Generated by Django 5.0.6 on 2025-06-04 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0049_alter_disciplinethemes_formcontrol'),
    ]

    operations = [
        migrations.AddField(
            model_name='planlineslink',
            name='can_be_copied_by_anyone',
            field=models.BooleanField(default=False, verbose_name='Каждый ли может скопировать программу'),
        ),
    ]
