# Generated by Django 5.0.6 on 2025-06-05 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0050_planlineslink_can_be_copied_by_anyone'),
    ]

    operations = [
        migrations.AddField(
            model_name='planlineslink',
            name='file',
            field=models.FileField(null=True, upload_to='rpd_generator/%Y-%m-%d/', verbose_name='Файл программы'),
        ),
        migrations.AddField(
            model_name='planlineslink',
            name='file_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
