# Generated by Django 5.0.6 on 2025-06-06 07:05

import app.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0051_planlineslink_file_planlineslink_file_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='planlineslink',
            name='last_accepted_file',
            field=models.FileField(null=True, storage=app.utils.OverwriteStorage, upload_to='rpd_generator/', verbose_name='Файл программы'),
        ),
        migrations.AlterField(
            model_name='planlineslink',
            name='file',
            field=models.FileField(null=True, storage=app.utils.OverwriteStorage, upload_to='rpd_generator/', verbose_name='Файл программы'),
        ),
    ]
