# Generated by Django 5.0.6 on 2025-06-07 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0052_planlineslink_last_accepted_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='planlineslink',
            name='uploaded_directly',
            field=models.BooleanField(default=False, null=True, verbose_name='Был ли файл загружен напрямую'),
        ),
        migrations.AlterField(
            model_name='planlineslink',
            name='file',
            field=models.FileField(null=True, upload_to='rpd_generator/', verbose_name='Файл программы'),
        ),
        migrations.AlterField(
            model_name='planlineslink',
            name='last_accepted_file',
            field=models.FileField(null=True, upload_to='rpd_generator/', verbose_name='Файл программы'),
        ),
    ]
