# Generated by Django 5.0.6 on 2025-06-07 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0053_planlineslink_uploaded_directly_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='planlineslink',
            name='can_upload_file_directly',
            field=models.BooleanField(default=False, null=True, verbose_name='Можно ли файл загрузать напрямую'),
        ),
    ]
