# Generated by Django 5.0.6 on 2025-06-07 16:39

from django.db import migrations

def update_user_confirmed(apps, schema_editor):
    PlanLinesLinkOld = apps.get_model("generator", "PlanLinesLink")
    PlanLinesLinkOld.objects.filter(status=3).update(
        user_confirmed=F('user_accepted')
    )

class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0054_planlineslink_can_upload_file_directly'),
    ]

    operations = [
        migrations.RunPython(update_user_confirmed)
    ]

