# Generated by Django 5.0.6 on 2025-06-07 16:39
from django.core.management import call_command
from django.db import migrations

def my_function(apps, schema_editor):
    call_command("add_default_num_in_fos")

class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0054_planlineslink_can_upload_file_directly'),
    ]

    operations = [
        migrations.RunPython(my_function)
    ]

