# Generated by Django 5.0.6 on 2025-06-22 05:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0055_auto_20250608_0039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disciplineworkhours',
            name='theme',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='generator.disciplinethemes'),
        ),
        migrations.AlterField(
            model_name='planlineslink',
            name='mira_id',
            field=models.IntegerField(verbose_name='id из UchPlanLines'),
        ),
    ]
