# Generated by Django 5.0.6 on 2025-07-10 02:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0056_alter_disciplineworkhours_theme_and_more'),
        ('rpd', '0044_linesdata_rpd_linesda_dis_b5fc98_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='planlineslink',
            index=models.Index(fields=['mira_id'], name='generator_p_mira_id_2c3629_idx'),
        ),
    ]
