# Generated by Django 5.0.14 on 2025-09-29 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0057_planlineslink_generator_p_mira_id_2c3629_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='planlineslink',
            name='last_accepted_file_sig',
            field=models.FileField(null=True, upload_to='signs/', verbose_name='Файл цифровой подписи'),
        ),
        migrations.AddField(
            model_name='planlineslink',
            name='last_accepted_file_sig_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='ID цифровой подписи'),
        ),
    ]
