# Generated by Django 5.0.14 on 2025-09-29 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0058_planlineslink_last_accepted_file_sig_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='planlineslink',
            old_name='last_accepted_file_sig_id',
            new_name='last_accepted_sig_id',
        ),
        migrations.RemoveField(
            model_name='planlineslink',
            name='last_accepted_file_sig',
        ),
        migrations.AddField(
            model_name='planlineslink',
            name='last_accepted_sig',
            field=models.TextField(blank=True, null=True),
        ),
    ]
