# Generated by Django 5.0.14 on 2025-10-07 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0059_rename_last_accepted_file_sig_id_planlineslink_last_accepted_sig_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='planlineslink',
            name='last_accepted_sig_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
