"""
Django settings for app project.

Generated by 'django-admin startproject' using Django 5.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""
import os
from pathlib import Path

import pendulum

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-!yh4!=+m_ey^u8oj8h&=rzr#oxq5jg=7k@y4@_*^rmhevyv*$j'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'constance',

    'rest_framework',
    'loginas',

    'rpd',
    'rpgen',
    'generator',
    'uplfile',
    'auths',
    'arim',
    'arim_library',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'app.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'app.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auths.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auths.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auths.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auths.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Irkutsk'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'

STATIC_ROOT = BASE_DIR / "static"

STATICFILES_DIRS = [
    BASE_DIR / "client" / "dist" / "spa",
]

DATABASE_ROUTERS = ["app.router.MainRouter", "app.router.RpdRouter", "app.router.LibraryRouter"]

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

BITRIX_SECRET_KEY = ""
BITRIX_CLIENT_ID = ""

LOGINAS_REDIRECT_URL = '/'

ENABLE_CACHE_FUNCTION_DECORATOR = False

ARIM_URL = "http://arim.istu.edu"


MEDIA_URL = '/uploads/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'uploads')

RPGEN_CONNECTION_STRING = ""


CONSTANCE_CONFIG = {
    'RPD_DISCIPLINES_ONLY_ZAV_CONFIRM_REQUIRED': ("""Безопасность жизнедеятельности
Инженерная и компьютерная графика
Иностранный язык
Информационные технологии
История России
Критическое и системное мышление
Математика
Метрология, стандартизация, сертификация
Основы деловой коммуникации
Основы инклюзивного взаимодействия
Основы проектной деятельности
Основы российской государственности
Правоведение
Сопротивление материалов
Теоретическая механика
Физика
Физическая культура и спорт
Философия
Химия
Экономика
Элективные курсы по физической культуре
Электротехника и электроник
Академическое письмо
Иностранный язык для магистрантов
Философия науки""", "Список дисциплин которые утверждаются без РОПа по приказу 258-О 2025 года", str),
}

CONSTANCE_BACKEND = 'constance.backends.database.DatabaseBackend'
SITE_URL = "https://app.istu.edu/oop"

pendulum.set_locale("ru")

from .local import *


