# Generated by Django 5.0.6 on 2024-07-05 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rpd', '0002_rpdfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='rpdfile',
            name='status',
            field=models.IntegerField(choices=[(1, 'Загружен'), (2, 'В обработке'), (3, 'На рассмотрении'), (4, 'Проверен')], default=1),
        ),
    ]
