# Generated by Django 5.0.6 on 2024-07-07 13:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rpd', '0003_rpdfile_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rpdfile',
            name='status',
            field=models.IntegerField(choices=[(0, 'Загружен'), (1, 'В обработке'), (2, 'На рассмотрении'), (3, 'Проверен')], default=(0, 'Загружен')),
        ),
        migrations.CreateModel(
            name='PlanData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('subtype', models.CharField(max_length=64, verbose_name='')),
                ('shifr', models.CharField(max_length=8, verbose_name='')),
                ('studyform', models.CharField(max_length=48, verbose_name='')),
                ('studylevel', models.CharField(max_length=64, verbose_name='')),
                ('studyprog', models.CharField(max_length=64, verbose_name='')),
                ('elementisweek', models.IntegerField(verbose_name='')),
                ('species', models.CharField(max_length=4096, verbose_name='')),
                ('usernum', models.IntegerField(verbose_name='')),
                ('whoratif', models.CharField(max_length=128, verbose_name='')),
                ('planname', models.CharField(max_length=256, verbose_name='')),
                ('kafcode', models.IntegerField(verbose_name='')),
                ('startyear', models.IntegerField(verbose_name='')),
                ('dviga', models.IntegerField(verbose_name='')),
                ('gviga', models.IntegerField(verbose_name='')),
                ('igazetweek', models.FloatField(verbose_name='')),
                ('semesteroncourse', models.IntegerField(verbose_name='')),
                ('gosdate', models.DateField(verbose_name='')),
                ('lastshifr', models.CharField(max_length=64, verbose_name='')),
                ('napr_e', models.CharField(max_length=1024, verbose_name='')),
                ('napr_t', models.CharField(max_length=1024, verbose_name='')),
                ('vuzname', models.CharField(max_length=256, verbose_name='')),
                ('head', models.CharField(max_length=256, verbose_name='')),
                ('faculty', models.CharField(max_length=256, verbose_name='')),
                ('file_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rpd.rpdfile', verbose_name='Файл')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
