# Generated by Django 5.0.6 on 2024-07-07 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rpd', '0004_alter_rpdfile_status_plandata'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plandata',
            old_name='elementisweek',
            new_name='elementsinweek',
        ),
        migrations.RenameField(
            model_name='plandata',
            old_name='semesteroncourse',
            new_name='semesteroncource',
        ),
        migrations.AddField(
            model_name='plandata',
            name='igahourzet',
            field=models.FloatField(null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='plandata',
            name='dviga',
            field=models.BooleanField(verbose_name=''),
        ),
        migrations.AlterField(
            model_name='plandata',
            name='faculty',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='plandata',
            name='gviga',
            field=models.BooleanField(verbose_name=''),
        ),
        migrations.AlterField(
            model_name='plandata',
            name='head',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='plandata',
            name='igazetweek',
            field=models.FloatField(null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='plandata',
            name='kafcode',
            field=models.IntegerField(null=True, verbose_name=''),
        ),
    ]
