# Generated by Django 5.0.6 on 2024-07-07 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rpd', '0005_rename_elementisweek_plandata_elementsinweek_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plandata',
            old_name='file_id',
            new_name='file',
        ),
    ]
