# Generated by Django 5.0.6 on 2024-07-08 16:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rpd', '0006_rename_file_id_plandata_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disciplines',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=256, verbose_name='')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LinesData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('dis', models.CharField(max_length=256, verbose_name='')),
                ('newdisid', models.CharField(blank=True, max_length=128, null=True, verbose_name='')),
                ('mustbesdudied', models.IntegerField(null=True, verbose_name='')),
                ('hoursinzet', models.IntegerField(null=True, verbose_name='')),
                ('caf', models.IntegerField(null=True, verbose_name='')),
                ('nocalccontrol', models.BooleanField(null=True, verbose_name='')),
                ('type', models.IntegerField(null=True, verbose_name='')),
                ('viewpract', models.IntegerField(null=True, verbose_name='')),
                ('viewobject', models.IntegerField(null=True, verbose_name='')),
                ('kompetences', models.CharField(blank=True, max_length=256, null=True, verbose_name='')),
                ('disid', models.ForeignKey(db_column='disid', on_delete=django.db.models.deletion.PROTECT, to='rpd.disciplines', verbose_name='')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rpd.plandata', verbose_name='')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
