# Generated by Django 5.0.6 on 2024-07-09 07:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rpd', '0007_disciplines_linesdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='SemesterData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('num', models.IntegerField(verbose_name='')),
                ('lekc', models.IntegerField(null=True, verbose_name='')),
                ('lab', models.IntegerField(null=True, verbose_name='')),
                ('pr', models.IntegerField(null=True, verbose_name='')),
                ('srs', models.IntegerField(null=True, verbose_name='')),
                ('ekzhour', models.IntegerField(null=True, verbose_name='')),
                ('zet', models.IntegerField(null=True, verbose_name='')),
                ('ekz', models.BooleanField(null=True, verbose_name='')),
                ('zach', models.BooleanField(null=True, verbose_name='')),
                ('kp_hour', models.IntegerField(null=True, verbose_name='')),
                ('kp', models.BooleanField(null=True, verbose_name='')),
                ('kr_hour', models.IntegerField(null=True, verbose_name='')),
                ('kr', models.BooleanField(null=True, verbose_name='')),
                ('zacho', models.IntegerField(null=True, verbose_name='')),
                ('eios', models.IntegerField(null=True, verbose_name='')),
                ('planlineid', models.ForeignKey(db_column='planlineid', on_delete=django.db.models.deletion.PROTECT, to='rpd.linesdata', verbose_name='')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
