# Generated by Django 5.0.6 on 2024-07-10 13:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rpd', '0008_semesterdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinesIndicators',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('competence_index', models.CharField(max_length=32, verbose_name='')),
                ('competence', models.CharField(max_length=2048, verbose_name='')),
                ('indicator_index', models.CharField(max_length=32, verbose_name='')),
                ('indicator', models.CharField(max_length=2048, verbose_name='')),
                ('planlineid', models.ForeignKey(db_column='planlineid', on_delete=django.db.models.deletion.PROTECT, to='rpd.linesdata', verbose_name='')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
