# Generated by Django 5.0.6 on 2024-07-10 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rpd', '0009_linesindicators'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linesindicators',
            name='competence',
            field=models.CharField(blank=True, max_length=2048, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='linesindicators',
            name='competence_index',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name=''),
        ),
    ]
