# Generated by Django 5.0.6 on 2024-07-10 15:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rpd', '0010_alter_linesindicators_competence_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExceptionNames',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=256, verbose_name='')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PlanDocuments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=256, verbose_name='')),
                ('type', models.IntegerField(verbose_name='')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='rpd.plandata', verbose_name='')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
