# Generated by Django 5.0.6 on 2024-07-10 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rpd', '0011_exceptionnames_plandocuments'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllowedNames',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=256, verbose_name='')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
