# Generated by Django 5.0.6 on 2024-07-16 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rpd', '0012_allowednames'),
    ]

    operations = [
        migrations.AddField(
            model_name='plandata',
            name='abbrprofile',
            field=models.CharField(default=0, max_length=12, verbose_name=''),
            preserve_default=False,
        ),
    ]
