# Generated by Django 5.0.6 on 2024-07-16 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rpd', '0013_plandata_abbrprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plandata',
            name='abbrprofile',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name=''),
        ),
    ]
