# Generated by Django 5.0.6 on 2024-07-16 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rpd', '0014_alter_plandata_abbrprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='linesdata',
            name='synchronize',
            field=models.BooleanField(default=0, verbose_name=''),
        ),
        migrations.AddField(
            model_name='linesindicators',
            name='synchronize',
            field=models.BooleanField(default=0, verbose_name=''),
        ),
        migrations.AddField(
            model_name='plandata',
            name='synchronize',
            field=models.BooleanField(default=0, verbose_name=''),
        ),
        migrations.AddField(
            model_name='plandocuments',
            name='synchronize',
            field=models.BooleanField(default=0, verbose_name=''),
        ),
        migrations.AddField(
            model_name='semesterdata',
            name='synchronize',
            field=models.BooleanField(default=0, verbose_name=''),
        ),
    ]
