# Generated by Django 5.0.6 on 2024-07-17 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rpd', '0015_linesdata_synchronize_linesindicators_synchronize_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='linesindicators',
            name='synchronize',
        ),
        migrations.RemoveField(
            model_name='plandata',
            name='synchronize',
        ),
        migrations.RemoveField(
            model_name='plandocuments',
            name='synchronize',
        ),
        migrations.RemoveField(
            model_name='semesterdata',
            name='synchronize',
        ),
        migrations.AlterField(
            model_name='linesdata',
            name='synchronize',
            field=models.BooleanField(default=1, verbose_name=''),
        ),
    ]
