# Generated by Django 5.0.6 on 2024-07-17 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rpd', '0016_remove_linesindicators_synchronize_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plandocuments',
            name='synchronize',
            field=models.BooleanField(default=False, verbose_name=''),
            preserve_default=False,
        ),
    ]
