# Generated by Django 5.0.6 on 2024-07-19 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rpd', '0017_plandocuments_synchronize'),
    ]

    operations = [
        migrations.AddField(
            model_name='plandocuments',
            name='manual',
            field=models.BooleanField(default=False, verbose_name=''),
        ),
    ]
