# Generated by Django 5.0.6 on 2024-07-20 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rpd', '0018_plandocuments_manual'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseDocuments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=64, verbose_name='')),
                ('type', models.IntegerField(verbose_name='')),
                ('bachelor', models.BooleanField(verbose_name='')),
                ('magistrate', models.BooleanField(verbose_name='')),
                ('spo', models.BooleanField(verbose_name='')),
                ('aspirant', models.BooleanField(verbose_name='')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
