# Generated by Django 5.0.6 on 2024-07-20 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rpd', '0019_basedocuments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basedocuments',
            name='aspirant',
            field=models.BooleanField(verbose_name='Аспирантура'),
        ),
        migrations.AlterField(
            model_name='basedocuments',
            name='bachelor',
            field=models.BooleanField(verbose_name='Бакалавр'),
        ),
        migrations.AlterField(
            model_name='basedocuments',
            name='magistrate',
            field=models.BooleanField(verbose_name='Магистратура'),
        ),
        migrations.AlterField(
            model_name='basedocuments',
            name='name',
            field=models.CharField(max_length=64, verbose_name='Наименование файла'),
        ),
        migrations.AlterField(
            model_name='basedocuments',
            name='spo',
            field=models.BooleanField(verbose_name='СПО'),
        ),
        migrations.AlterField(
            model_name='basedocuments',
            name='type',
            field=models.IntegerField(verbose_name='Тип'),
        ),
    ]
