# Generated by Django 5.0.6 on 2024-07-20 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rpd', '0020_alter_basedocuments_aspirant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='basedocuments',
            name='specialist',
            field=models.BooleanField(default=1, verbose_name='Специалитет'),
            preserve_default=False,
        ),
    ]
