# Generated by Django 5.0.6 on 2024-07-22 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rpd', '0021_basedocuments_specialist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linesdata',
            name='kompetences',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name=''),
        ),
    ]
