# Generated by Django 5.0.6 on 2024-07-22 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rpd', '0022_alter_linesdata_kompetences'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plandata',
            name='gosdate',
            field=models.DateField(null=True, verbose_name=''),
        ),
    ]
