# Generated by Django 5.0.6 on 2024-07-30 02:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rpd', '0023_alter_plandata_gosdate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Competence',
        ),
        migrations.AlterField(
            model_name='linesdata',
            name='disid',
            field=models.ForeignKey(db_column='disid', on_delete=django.db.models.deletion.CASCADE, to='rpd.disciplines', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='linesdata',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rpd.plandata', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='linesindicators',
            name='planlineid',
            field=models.ForeignKey(db_column='planlineid', on_delete=django.db.models.deletion.CASCADE, to='rpd.linesdata', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='plandata',
            name='file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rpd.rpdfile', verbose_name='Файл'),
        ),
        migrations.AlterField(
            model_name='plandocuments',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rpd.plandata', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='semesterdata',
            name='planlineid',
            field=models.ForeignKey(db_column='planlineid', on_delete=django.db.models.deletion.CASCADE, to='rpd.linesdata', verbose_name=''),
        ),
    ]
