# Generated by Django 5.0.6 on 2024-08-07 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rpd', '0024_delete_competence_alter_linesdata_disid_and_more'),
        ('rpd', '0024_discipline_indikator_plan_plancompetence_and_more'),
    ]

    operations = [
    ]
