# Generated by Django 5.0.6 on 2024-07-29 08:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rpd', '0024_discipline_indikator_plan_plancompetence_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanLinesLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('cadmission', models.IntegerField(verbose_name='')),
                ('mira_id', models.IntegerField(verbose_name='')),
                ('status', models.IntegerField(choices=[(0, 'Назначен'), (1, 'Заполняется'), (2, 'Отправлен на проверку'), (3, 'Подтвержден'), (4, 'Требуются правки')], default=(0, 'Назначен'))),
                ('planlines', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rpd.linesdata', verbose_name='')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
