# Generated by Django 5.0.6 on 2024-07-30 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rpd', '0025_planlineslink'),
    ]

    operations = [
        migrations.AddField(
            model_name='planlineslink',
            name='mira_line_id',
            field=models.IntegerField(default=0, verbose_name=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='planlineslink',
            name='status',
            field=models.IntegerField(choices=[(0, 'Назначен'), (1, 'Заполняется'), (2, 'Отправлен на проверку'), (3, 'Подтвержден'), (4, 'Требуются правки')], default=(0, 'Назначен'), verbose_name=''),
        ),
    ]
