# Generated by Django 5.0.6 on 2024-08-07 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rpd', '0025_merge_20240807_1645'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Discipline',
        ),
        migrations.DeleteModel(
            name='Indikator',
        ),
        migrations.DeleteModel(
            name='Plan',
        ),
        migrations.DeleteModel(
            name='PlanCompetence',
        ),
        migrations.DeleteModel(
            name='PlanIndikator',
        ),
        migrations.DeleteModel(
            name='Planlines',
        ),
        migrations.DeleteModel(
            name='Semestr',
        ),
        migrations.AddField(
            model_name='plandata',
            name='gosdocument',
            field=models.IntegerField(null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='plandata',
            name='gostype',
            field=models.FloatField(null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='rpdfile',
            name='status',
            field=models.IntegerField(choices=[(0, 'Загружен'), (1, 'На рассмотрении'), (2, 'Принят, ожидает синхронизации'), (3, 'Принят, синхронизируется'), (4, 'Принят, уже в АИС')], default=0),
        ),
    ]
