# Generated by Django 5.0.6 on 2024-08-06 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rpd', '0024_delete_competence_alter_linesdata_disid_and_more'),
        ('rpd', '0026_planlineslink_mira_line_id_and_more'),
    ]

    operations = [
    ]
