# Generated by Django 5.0.6 on 2024-08-09 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rpd', '0025_merge_20240808_2322'),
        ('rpd', '0026_delete_discipline_delete_indikator_delete_plan_and_more'),
    ]

    operations = [
    ]
