# Generated by Django 5.0.6 on 2024-08-09 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rpd', '0027_merge_20240809_1103'),
    ]

    operations = [
        migrations.AddField(
            model_name='plandata',
            name='mira_id',
            field=models.IntegerField(blank=True, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='plandocuments',
            name='mira_id',
            field=models.IntegerField(blank=True, null=True, verbose_name=''),
        ),
    ]
