# Generated by Django 5.0.6 on 2024-08-21 06:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rpd', '0028_plandata_mira_id_plandocuments_mira_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allowednames',
            name='name',
            field=models.TextField(verbose_name=''),
        ),
        migrations.AlterField(
            model_name='basedocuments',
            name='name',
            field=models.TextField(verbose_name='Наименование файла'),
        ),
        migrations.AlterField(
            model_name='disciplines',
            name='name',
            field=models.TextField(verbose_name=''),
        ),
        migrations.AlterField(
            model_name='exceptionnames',
            name='name',
            field=models.TextField(verbose_name=''),
        ),
        migrations.AlterField(
            model_name='linesdata',
            name='dis',
            field=models.TextField(verbose_name=''),
        ),
        migrations.AlterField(
            model_name='linesdata',
            name='kompetences',
            field=models.TextField(blank=True, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='linesdata',
            name='newdisid',
            field=models.TextField(blank=True, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='linesindicators',
            name='competence',
            field=models.TextField(blank=True, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='linesindicators',
            name='competence_index',
            field=models.TextField(blank=True, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='linesindicators',
            name='indicator',
            field=models.TextField(verbose_name=''),
        ),
        migrations.AlterField(
            model_name='linesindicators',
            name='indicator_index',
            field=models.TextField(verbose_name=''),
        ),
        migrations.AlterField(
            model_name='linesindicators',
            name='planlineid',
            field=models.ForeignKey(db_column='planlineid', on_delete=django.db.models.deletion.CASCADE, related_name='indicators', to='rpd.linesdata', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='plandata',
            name='abbrprofile',
            field=models.TextField(blank=True, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='plandata',
            name='faculty',
            field=models.TextField(blank=True, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='plandata',
            name='head',
            field=models.TextField(blank=True, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='plandata',
            name='lastshifr',
            field=models.TextField(verbose_name=''),
        ),
        migrations.AlterField(
            model_name='plandata',
            name='napr_e',
            field=models.TextField(verbose_name=''),
        ),
        migrations.AlterField(
            model_name='plandata',
            name='napr_t',
            field=models.TextField(verbose_name=''),
        ),
        migrations.AlterField(
            model_name='plandata',
            name='planname',
            field=models.TextField(verbose_name=''),
        ),
        migrations.AlterField(
            model_name='plandata',
            name='shifr',
            field=models.TextField(verbose_name=''),
        ),
        migrations.AlterField(
            model_name='plandata',
            name='species',
            field=models.TextField(verbose_name=''),
        ),
        migrations.AlterField(
            model_name='plandata',
            name='studyform',
            field=models.TextField(verbose_name=''),
        ),
        migrations.AlterField(
            model_name='plandata',
            name='studylevel',
            field=models.TextField(verbose_name=''),
        ),
        migrations.AlterField(
            model_name='plandata',
            name='studyprog',
            field=models.TextField(verbose_name=''),
        ),
        migrations.AlterField(
            model_name='plandata',
            name='subtype',
            field=models.TextField(verbose_name=''),
        ),
        migrations.AlterField(
            model_name='plandata',
            name='vuzname',
            field=models.TextField(verbose_name=''),
        ),
        migrations.AlterField(
            model_name='plandata',
            name='whoratif',
            field=models.TextField(verbose_name=''),
        ),
        migrations.AlterField(
            model_name='plandocuments',
            name='name',
            field=models.TextField(verbose_name=''),
        ),
        migrations.AlterField(
            model_name='rpdfile',
            name='title',
            field=models.TextField(verbose_name='Наименование файла'),
        ),
        migrations.AlterField(
            model_name='semesterdata',
            name='planlineid',
            field=models.ForeignKey(db_column='planlineid', on_delete=django.db.models.deletion.CASCADE, related_name='semesters', to='rpd.linesdata', verbose_name=''),
        ),
    ]
