# Generated by Django 5.0.6 on 2024-08-23 05:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rpd', '0029_alter_allowednames_name_alter_basedocuments_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linesdata',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='rpd.plandata', verbose_name=''),
        ),
    ]
