# Generated by Django 5.0.6 on 2024-08-29 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rpd', '0031_alter_allowednames_name_alter_disciplines_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semesterdata',
            name='zet',
            field=models.FloatField(null=True),
        ),
    ]
