# Generated by Django 5.0.6 on 2024-10-29 03:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rpd', '0032_alter_semesterdata_zet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plandocuments',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_documents', to='rpd.plandata'),
        ),
    ]
