# Generated by Django 5.0.6 on 2024-10-31 03:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rpd', '0034_documentstypes_basedocuments_new_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='linesdata',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rpd.linesdata'),
        ),
    ]
