# Generated by Django 5.0.6 on 2024-11-21 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rpd', '0035_linesdata_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rpdfile',
            name='file',
            field=models.FileField(upload_to='rpd_plan/%Y-%m-%d/', verbose_name='Файл РПД'),
        ),
    ]
