# Generated by Django 5.1.7 on 2025-03-19 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rpd', '0036_alter_rpdfile_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plandocuments',
            name='synchronize',
            field=models.BooleanField(default=True),
        ),
    ]
