# Generated by Django 5.0.6 on 2025-03-31 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rpd', '0037_alter_plandocuments_synchronize'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plandata',
            name='gosdocument',
            field=models.TextField(null=True),
        ),
    ]
