# Generated by Django 5.0.6 on 2025-05-02 03:25

import django.db.models.deletion
from django.db import migrations, models


def update_file_plandata_field(apps, schema_editor):
    PlanData = apps.get_model("rpd", "PlanData")
    RPDFile = apps.get_model("rpd", "RPDFile")
    for p in PlanData.objects.select_related().all():
        p.file.plandata_id = p.id
        p.file.save()


class Migration(migrations.Migration):

    dependencies = [
        ('rpd', '0038_alter_plandata_gosdocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='rpdfile',
            name='plandata',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rpd.plandata'),
        ),
        migrations.AlterField(
            model_name='plandata',
            name='file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_data_item', to='rpd.rpdfile', verbose_name='Файл'),
        ),
        migrations.RunPython(update_file_plandata_field)
    ]
