# Generated by Django 5.0.6 on 2025-05-02 03:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rpd', '0039_rpdfile_plandata_alter_plandata_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plandata',
            name='file',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='plan_data_item', to='rpd.rpdfile', verbose_name='Файл'),
        ),
    ]
