# Generated by Django 5.0.6 on 2025-05-13 08:14

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rpd', '0040_alter_plandata_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='basedocuments',
            name='can_upload',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(choices=[(0, 'Руководитель программы'), (1, 'Учебный отдел'), (2, 'Кафедра')], default=0), default=[], size=None),
        ),
    ]
