# Generated by Django 5.0.6 on 2025-05-26 02:57

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rpd', '0041_basedocuments_can_upload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basedocuments',
            name='can_upload',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(choices=[(0, 'Руководитель программы'), (1, 'Учебный отдел'), (2, 'Кафедра')], default=0), default=list, size=None),
        ),
    ]
