# Generated by Django 5.0.6 on 2025-06-11 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rpd', '0042_alter_basedocuments_can_upload'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='plandata',
            index=models.Index(fields=['studylevel'], name='rpd_plandat_studyle_b4a9fe_idx'),
        ),
        migrations.AddIndex(
            model_name='plandata',
            index=models.Index(fields=['startyear'], name='rpd_plandat_startye_658aa4_idx'),
        ),
        migrations.AddIndex(
            model_name='plandata',
            index=models.Index(fields=['studylevel', 'startyear'], name='rpd_plandat_studyle_1a2c26_idx'),
        ),
    ]
