# Generated by Django 5.0.6 on 2025-07-10 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rpd', '0043_plandata_rpd_plandat_studyle_b4a9fe_idx_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='linesdata',
            index=models.Index(fields=['dis', 'type', 'synchronize'], name='rpd_linesda_dis_b5fc98_idx'),
        ),
        migrations.AddIndex(
            model_name='plandata',
            index=models.Index(fields=['abbrprofile', 'startyear'], name='rpd_plandat_abbrpro_b6da24_idx'),
        ),
    ]
