# Generated by Django 5.0.6 on 2025-07-10 03:58

from django.db import migrations, models


def fill_mira_id(apps, schema_editor):
    LinesData = apps.get_model("rpd", "LinesData")
    PlanLinesLink = apps.get_model("generator", "PlanLinesLink")

    lines_data = LinesData.objects.all()

    for lines in lines_data:
        plan_lines_link = PlanLinesLink.objects.filter(planlines_id=lines.id).first()
        if plan_lines_link:
            lines.mira_id = plan_lines_link.mira_id
            lines.save()

class Migration(migrations.Migration):

    dependencies = [
        ('rpd', '0044_linesdata_rpd_linesda_dis_b5fc98_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='linesdata',
            name='mira_id',
            field=models.IntegerField(null=True, verbose_name='Ссылка на uchplanlines'),
        ),
        migrations.RunPython(fill_mira_id, migrations.RunPython.noop),
    ]
