# Generated by Django 5.0.14 on 2025-11-01 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rpd', '0045_linesdata_mira_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allowednames',
            name='is_deleted',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='basedocuments',
            name='is_deleted',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='disciplines',
            name='is_deleted',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='documentstypes',
            name='is_deleted',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='exceptionnames',
            name='is_deleted',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='linesdata',
            name='is_deleted',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='linesindicators',
            name='is_deleted',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='plandata',
            name='is_deleted',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='plandocuments',
            name='is_deleted',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='rpdfile',
            name='is_deleted',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='semesterdata',
            name='is_deleted',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
