# Generated by Django 5.0.14 on 2025-12-10 06:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rpd', '0046_alter_allowednames_is_deleted_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('is_deleted', models.BooleanField(default=False, null=True)),
                ('competence_index', models.TextField(blank=True, null=True)),
                ('competence', models.TextField(blank=True, null=True)),
                ('semester', models.IntegerField()),
                ('ekz', models.BooleanField(null=True)),
                ('zach', models.BooleanField(null=True)),
                ('zacho', models.BooleanField(null=True)),
                ('kp', models.BooleanField(null=True)),
                ('kr', models.BooleanField(null=True)),
                ('planlineid', models.ForeignKey(db_column='planlineid', on_delete=django.db.models.deletion.CASCADE, related_name='competence_schemes', to='rpd.linesdata')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
