# Generated by Django 5.0.14 on 2025-12-13 04:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competence_passport', '0001_initial'),
        ('rpd', '0046_alter_allowednames_is_deleted_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompetenceRelations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('is_deleted', models.BooleanField(default=False, null=True)),
                ('competence_index', models.TextField(blank=True, null=True)),
                ('competence', models.TextField(blank=True, null=True)),
                ('relations', models.TextField(blank=True, null=True)),
                ('plan', models.ForeignKey(db_column='plan_id', on_delete=django.db.models.deletion.CASCADE, related_name='competence_relations', to='rpd.plandata')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
