# Generated by Django 5.0.14 on 2026-02-25 06:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competence_passport', '0003_competence'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scheme',
            name='competence',
        ),
        migrations.AddField(
            model_name='scheme',
            name='competence_id',
            field=models.ForeignKey(blank=True, db_column='competence_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='competence_schemes', to='competence_passport.competence'),
        ),
    ]
