# Generated by Django 5.0.14 on 2026-02-25 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competence_passport', '0004_remove_scheme_competence_scheme_competence_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scheme',
            name='competence_index',
        ),
    ]
