# Generated by Django 5.0.14 on 2026-02-25 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competence_passport', '0005_remove_scheme_competence_index'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CompetenceRelations',
        ),
    ]
